# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/yang_mills
pkgincludedir = $(includedir)/yang_mills
pkglibdir = $(libdir)/yang_mills
pkglibexecdir = $(libexecdir)/yang_mills
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = conf_check$(EXEEXT) debug_rng$(EXEEXT) \
	debug_su2$(EXEEXT) debug_su2_adj$(EXEEXT) debug_sun$(EXEEXT) \
	debug_u1$(EXEEXT) yang_mills_local$(EXEEXT) \
	yang_mills_polycorr$(EXEEXT) yang_mills_polycorr_long$(EXEEXT) \
	yang_mills_polycorradj$(EXEEXT) yang_mills_t0$(EXEEXT) \
	yang_mills_tube_conn$(EXEEXT) \
	yang_mills_tube_conn_long$(EXEEXT) \
	yang_mills_tube_disc$(EXEEXT) yang_mills_tracedef$(EXEEXT) \
	yang_mills_local_pt$(EXEEXT) \
	yang_mills_local_pt_multicanonic$(EXEEXT) \
	yang_mills_gradient_flow$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 = ./lib/aligncheck.$(OBJEXT)
am__objects_2 = ./lib/dSFMT.$(OBJEXT)
am__objects_3 = ./lib/endianness.$(OBJEXT)
am__objects_4 = ./lib/function_pointers.$(OBJEXT)
am__objects_5 = ./lib/gparam.$(OBJEXT)
am__objects_6 = ./lib/random.$(OBJEXT)
am__objects_7 = ./lib/su2.$(OBJEXT) ./lib/su2_upd.$(OBJEXT)
am__objects_8 = ./lib/sun_aux.$(OBJEXT) ./lib/sun.$(OBJEXT) \
	./lib/sun_upd.$(OBJEXT)
am__objects_9 = ./lib/u1.$(OBJEXT) ./lib/u1_upd.$(OBJEXT)
am_conf_check_OBJECTS = ./src/conf_check.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_9)
conf_check_OBJECTS = $(am_conf_check_OBJECTS)
conf_check_LDADD = $(LDADD)
am_debug_rng_OBJECTS = ./src/debug_rng.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_6)
debug_rng_OBJECTS = $(am_debug_rng_OBJECTS)
debug_rng_LDADD = $(LDADD)
am_debug_su2_OBJECTS = ./src/debug_su2.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7)
debug_su2_OBJECTS = $(am_debug_su2_OBJECTS)
debug_su2_LDADD = $(LDADD)
am_debug_su2_adj_OBJECTS = ./src/debug_su2_adj.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7)
debug_su2_adj_OBJECTS = $(am_debug_su2_adj_OBJECTS)
debug_su2_adj_LDADD = $(LDADD)
am_debug_sun_OBJECTS = ./src/debug_sun.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8)
debug_sun_OBJECTS = $(am_debug_sun_OBJECTS)
debug_sun_LDADD = $(LDADD)
am_debug_u1_OBJECTS = ./src/debug_u1.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_5) \
	$(am__objects_6) $(am__objects_9)
debug_u1_OBJECTS = $(am_debug_u1_OBJECTS)
debug_u1_LDADD = $(LDADD)
am__objects_10 = ./lib/gauge_conf_def.$(OBJEXT) \
	./lib/gauge_conf_meas.$(OBJEXT) \
	./lib/gauge_conf_multilevel.$(OBJEXT) \
	./lib/gauge_conf_upd.$(OBJEXT) \
	./lib/gauge_conf_paral_temp.$(OBJEXT) \
	./lib/gauge_conf_multicanonic.$(OBJEXT)
am__objects_11 = ./lib/geometry.$(OBJEXT)
am__objects_12 = ./lib/tens_prod.$(OBJEXT) \
	./lib/tens_prod_adj.$(OBJEXT)
am_yang_mills_gradient_flow_OBJECTS =  \
	./src/yang_mills_gradient_flow.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_gradient_flow_OBJECTS =  \
	$(am_yang_mills_gradient_flow_OBJECTS)
yang_mills_gradient_flow_LDADD = $(LDADD)
am_yang_mills_local_OBJECTS = ./src/yang_mills_local.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_local_OBJECTS = $(am_yang_mills_local_OBJECTS)
yang_mills_local_LDADD = $(LDADD)
am_yang_mills_local_pt_OBJECTS = ./src/yang_mills_local_pt.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_local_pt_OBJECTS = $(am_yang_mills_local_pt_OBJECTS)
yang_mills_local_pt_LDADD = $(LDADD)
am_yang_mills_local_pt_multicanonic_OBJECTS =  \
	./src/yang_mills_local_pt_multicanonic.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_local_pt_multicanonic_OBJECTS =  \
	$(am_yang_mills_local_pt_multicanonic_OBJECTS)
yang_mills_local_pt_multicanonic_LDADD = $(LDADD)
am_yang_mills_polycorr_OBJECTS = ./src/yang_mills_polycorr.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_polycorr_OBJECTS = $(am_yang_mills_polycorr_OBJECTS)
yang_mills_polycorr_LDADD = $(LDADD)
am_yang_mills_polycorr_long_OBJECTS =  \
	./src/yang_mills_polycorr_long.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_polycorr_long_OBJECTS =  \
	$(am_yang_mills_polycorr_long_OBJECTS)
yang_mills_polycorr_long_LDADD = $(LDADD)
am_yang_mills_polycorradj_OBJECTS =  \
	./src/yang_mills_polycorradj.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_polycorradj_OBJECTS = $(am_yang_mills_polycorradj_OBJECTS)
yang_mills_polycorradj_LDADD = $(LDADD)
am_yang_mills_t0_OBJECTS = ./src/yang_mills_t0.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_t0_OBJECTS = $(am_yang_mills_t0_OBJECTS)
yang_mills_t0_LDADD = $(LDADD)
am_yang_mills_tracedef_OBJECTS = ./src/yang_mills_tracedef.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_10) $(am__objects_11) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_12) $(am__objects_9)
yang_mills_tracedef_OBJECTS = $(am_yang_mills_tracedef_OBJECTS)
yang_mills_tracedef_LDADD = $(LDADD)
am_yang_mills_tube_conn_OBJECTS =  \
	./src/yang_mills_tube_conn.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_tube_conn_OBJECTS = $(am_yang_mills_tube_conn_OBJECTS)
yang_mills_tube_conn_LDADD = $(LDADD)
am_yang_mills_tube_conn_long_OBJECTS =  \
	./src/yang_mills_tube_conn_long.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_tube_conn_long_OBJECTS =  \
	$(am_yang_mills_tube_conn_long_OBJECTS)
yang_mills_tube_conn_long_LDADD = $(LDADD)
am_yang_mills_tube_disc_OBJECTS =  \
	./src/yang_mills_tube_disc.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_10) $(am__objects_11) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_12) $(am__objects_9)
yang_mills_tube_disc_OBJECTS = $(am_yang_mills_tube_disc_OBJECTS)
yang_mills_tube_disc_LDADD = $(LDADD)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(conf_check_SOURCES) $(debug_rng_SOURCES) \
	$(debug_su2_SOURCES) $(debug_su2_adj_SOURCES) \
	$(debug_sun_SOURCES) $(debug_u1_SOURCES) \
	$(yang_mills_gradient_flow_SOURCES) \
	$(yang_mills_local_SOURCES) $(yang_mills_local_pt_SOURCES) \
	$(yang_mills_local_pt_multicanonic_SOURCES) \
	$(yang_mills_polycorr_SOURCES) \
	$(yang_mills_polycorr_long_SOURCES) \
	$(yang_mills_polycorradj_SOURCES) $(yang_mills_t0_SOURCES) \
	$(yang_mills_tracedef_SOURCES) $(yang_mills_tube_conn_SOURCES) \
	$(yang_mills_tube_conn_long_SOURCES) \
	$(yang_mills_tube_disc_SOURCES)
DIST_SOURCES = $(conf_check_SOURCES) $(debug_rng_SOURCES) \
	$(debug_su2_SOURCES) $(debug_su2_adj_SOURCES) \
	$(debug_sun_SOURCES) $(debug_u1_SOURCES) \
	$(yang_mills_gradient_flow_SOURCES) \
	$(yang_mills_local_SOURCES) $(yang_mills_local_pt_SOURCES) \
	$(yang_mills_local_pt_multicanonic_SOURCES) \
	$(yang_mills_polycorr_SOURCES) \
	$(yang_mills_polycorr_long_SOURCES) \
	$(yang_mills_polycorradj_SOURCES) $(yang_mills_t0_SOURCES) \
	$(yang_mills_tracedef_SOURCES) $(yang_mills_tube_conn_SOURCES) \
	$(yang_mills_tube_conn_long_SOURCES) \
	$(yang_mills_tube_disc_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS README compile depcomp \
	install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/missing autoconf
AUTOHEADER = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/missing autoheader
AUTOMAKE = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O3
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm -lcrypto 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/missing makeinfo
MKDIR_P = /bin/mkdir -p
N_c = 3
Num_levels = 
Num_threads = 1
OBJEXT = o
OPENMP_CFLAGS = 
PACKAGE = yang_mills
PACKAGE_BUGREPORT = claudio.bonati82@gmail.com
PACKAGE_NAME = yang_mills
PACKAGE_STRING = yang_mills 0.7.3
PACKAGE_TARNAME = yang_mills
PACKAGE_URL = 
PACKAGE_VERSION = 0.7.3
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
ST_dim = 
VERSION = 0.7.3
abs_builddir = /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread
abs_srcdir = /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread
abs_top_builddir = /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread
abs_top_srcdir = /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /mnt/c/Users/Asus/Desktop/yang-mills-hpt-multithread/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
align = ./include/aligncheck.h \
        ./lib/aligncheck.c

dSFMT = ./include/dSFMT-common.h \
        ./include/dSFMT.h \
        ./include/dSFMT-params11213.h \
        ./include/dSFMT-params1279.h \
        ./include/dSFMT-params132049.h \
        ./include/dSFMT-params19937.h \
        ./include/dSFMT-params216091.h \
        ./include/dSFMT-params2203.h \
        ./include/dSFMT-params4253.h \
        ./include/dSFMT-params44497.h \
        ./include/dSFMT-params521.h \
        ./include/dSFMT-params86243.h \
        ./include/dSFMT-params.h \
        ./lib/dSFMT.c

endian = ./include/endianness.h  \
         ./lib/endianness.c 

funcpoint = ./include/function_pointers.h \
            ./lib/function_pointers.c

gauge_conf = ./include/gauge_conf.h \
             ./lib/gauge_conf_def.c \
             ./lib/gauge_conf_meas.c \
             ./lib/gauge_conf_multilevel.c \
             ./lib/gauge_conf_upd.c \
						 ./lib/gauge_conf_paral_temp.c \
						 ./lib/gauge_conf_multicanonic.c

geometry = ./include/geometry.h \
           ./lib/geometry.c

gparam = ./include/gparam.h \
         ./lib/gparam.c

random = ./include/myrngparam.h \
         ./include/random.h \
         ./lib/random.c 

su2 = ./include/su2.h \
      ./include/su2_upd.h \
      ./lib/su2.c \
      ./lib/su2_upd.c 

sun = ./include/sun_aux.h \
      ./include/sun.h \
      ./include/sun_upd.h \
      ./lib/sun_aux.c \
      ./lib/sun.c \
      ./lib/sun_upd.c 

tens_prod = ./include/tens_prod.h \
            ./include/tens_prod_adj.h \
            ./lib/tens_prod.c \
            ./lib/tens_prod_adj.c

u1 = ./include/u1.h \
     ./include/u1_upd.h \
     ./lib/u1.c \
     ./lib/u1_upd.c

conf_check_SOURCES = ./src/conf_check.c \
                   $(align) \
                   $(dSFMT) \
                   $(endian) \
                   $(funcpoint) \
                   $(gparam) \
                   $(random) \
                   $(su2) \
                   $(sun) \
                   $(u1) 

debug_rng_SOURCES = ./src/debug_rng.c \
                  $(align) \
                  $(dSFMT) \
                  $(random)

debug_su2_SOURCES = ./src/debug_su2.c \
                  $(align) \
                  $(dSFMT) \
                  $(endian) \
                  $(gparam) \
                  ./include/macro.h \
                  $(random) \
                  $(su2)

debug_su2_adj_SOURCES = ./src/debug_su2_adj.c \
                      $(align) \
                      $(dSFMT) \
                      $(endian) \
                      $(gparam) \
                      ./include/macro.h \
                      $(random) \
                      $(su2) 

debug_sun_SOURCES = ./src/debug_sun.c \
                  $(align) \
                  $(dSFMT) \
                  $(endian) \
                  $(gparam) \
                  ./include/macro.h \
                  $(random) \
                  $(su2) \
                  $(sun)

debug_u1_SOURCES = ./src/debug_u1.c \
                  $(align) \
                  $(dSFMT) \
                  $(endian) \
                  $(gparam) \
                  ./include/macro.h \
                  $(random) \
                  $(u1)

yang_mills_local_SOURCES = ./src/yang_mills_local.c \
                          $(align) \
                          $(dSFMT)  \
                          $(endian) \
                          $(funcpoint) \
                          $(gauge_conf) \
                          $(geometry) \
                          $(gparam) \
                          ./include/macro.h \
                          $(random) \
                          $(su2) \
                          $(sun) \
                          $(tens_prod) \
                          $(u1) 

yang_mills_polycorr_SOURCES = ./src/yang_mills_polycorr.c \
                             $(align) \
                             $(dSFMT)  \
                             $(endian) \
                             $(funcpoint) \
                             $(gauge_conf) \
                             $(geometry) \
                             $(gparam) \
                             ./include/macro.h \
                             $(random) \
                             $(su2) \
                             $(sun) \
                             $(tens_prod) \
                             $(u1) 

yang_mills_polycorr_long_SOURCES = ./src/yang_mills_polycorr_long.c \
                                  $(align) \
                                  $(dSFMT)  \
                                  $(endian) \
                                  $(funcpoint) \
                                  $(gauge_conf) \
                                  $(geometry) \
                                  $(gparam) \
                                  ./include/macro.h \
                                  $(random) \
                                  $(su2) \
                                  $(sun) \
                                  $(tens_prod) \
                                  $(u1) 

yang_mills_polycorradj_SOURCES = ./src/yang_mills_polycorradj.c \
                                $(align) \
                                $(dSFMT)  \
                                $(endian) \
                                $(funcpoint) \
                                $(gauge_conf) \
                                $(geometry) \
                                $(gparam) \
                                ./include/macro.h \
                                $(random) \
                                $(su2) \
                                $(sun) \
                                $(tens_prod) \
                                $(u1) 

yang_mills_t0_SOURCES = ./src/yang_mills_t0.c \
                       $(align) \
                       $(dSFMT)  \
                       $(endian) \
                       $(funcpoint) \
                       $(gauge_conf) \
                       $(geometry) \
                       $(gparam) \
                       ./include/macro.h \
                       $(random) \
                       $(su2) \
                       $(sun) \
                       $(tens_prod) \
                       $(u1) 

yang_mills_tube_conn_SOURCES = ./src/yang_mills_tube_conn.c \
                             $(align) \
                             $(dSFMT)  \
                             $(endian) \
                             $(funcpoint) \
                             $(gauge_conf) \
                             $(geometry) \
                             $(gparam) \
                             ./include/macro.h \
                             $(random) \
                             $(su2) \
                             $(sun) \
                             $(tens_prod) \
                             $(u1) 

yang_mills_tube_conn_long_SOURCES = ./src/yang_mills_tube_conn_long.c \
                                  $(align) \
                                  $(dSFMT)  \
                                  $(endian) \
                                  $(funcpoint) \
                                  $(gauge_conf) \
                                  $(geometry) \
                                  $(gparam) \
                                  ./include/macro.h \
                                  $(random) \
                                  $(su2) \
                                  $(sun) \
                                  $(tens_prod) \
                                  $(u1) 

yang_mills_tube_disc_SOURCES = ./src/yang_mills_tube_disc.c \
                             $(align) \
                             $(dSFMT)  \
                             $(endian) \
                             $(funcpoint) \
                             $(gauge_conf) \
                             $(geometry) \
                             $(gparam) \
                             ./include/macro.h \
                             $(random) \
                             $(su2) \
                             $(sun) \
                             $(tens_prod) \
                             $(u1) 

yang_mills_tracedef_SOURCES = ./src/yang_mills_tracedef.c \
                            $(align) \
                            $(dSFMT)  \
                            $(endian) \
                            $(funcpoint) \
                            $(gauge_conf) \
                            $(geometry) \
                            $(gparam) \
                            ./include/macro.h \
                            $(random) \
                            $(su2) \
                            $(sun) \
                            $(tens_prod) \
                            $(u1) 

yang_mills_local_pt_SOURCES = ./src/yang_mills_local_pt.c \
                          $(align) \
                          $(dSFMT)  \
                          $(endian) \
                          $(funcpoint) \
                          $(gauge_conf) \
                          $(geometry) \
                          $(gparam) \
                          ./include/macro.h \
                          $(random) \
                          $(su2) \
                          $(sun) \
                          $(tens_prod) \
                          $(u1)

yang_mills_local_pt_multicanonic_SOURCES = ./src/yang_mills_local_pt_multicanonic.c \
                          $(align) \
                          $(dSFMT)  \
                          $(endian) \
                          $(funcpoint) \
                          $(gauge_conf) \
                          $(geometry) \
                          $(gparam) \
                          ./include/macro.h \
                          $(random) \
                          $(su2) \
                          $(sun) \
                          $(tens_prod) \
                          $(u1)

yang_mills_gradient_flow_SOURCES = ./src/yang_mills_gradient_flow.c \
                       $(align) \
                       $(dSFMT)  \
                       $(endian) \
                       $(funcpoint) \
                       $(gauge_conf) \
                       $(geometry) \
                       $(gparam) \
                       ./include/macro.h \
                       $(random) \
                       $(su2) \
                       $(sun) \
                       $(tens_prod) \
                       $(u1)

AM_CFLAGS = -std=c99 -O3 -Wall -Wextra -Werror -pedantic -Wconversion 
CLEANFILES = dati.dat chi_prime_cool.dat log.dat dati.log conf.dat* ml.dat template_input.in swap_acc.dat* swap_track.dat* multicanonic_acc.dat* topo_tcorr_cool.dat*
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) ./src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) ./src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
./src/conf_check.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
lib/$(am__dirstamp):
	@$(MKDIR_P) ./lib
	@: > lib/$(am__dirstamp)
lib/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) ./lib/$(DEPDIR)
	@: > lib/$(DEPDIR)/$(am__dirstamp)
./lib/aligncheck.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/dSFMT.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/endianness.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/function_pointers.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gparam.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/random.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/su2.$(OBJEXT): lib/$(am__dirstamp) lib/$(DEPDIR)/$(am__dirstamp)
./lib/su2_upd.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/sun_aux.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/sun.$(OBJEXT): lib/$(am__dirstamp) lib/$(DEPDIR)/$(am__dirstamp)
./lib/sun_upd.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/u1.$(OBJEXT): lib/$(am__dirstamp) lib/$(DEPDIR)/$(am__dirstamp)
./lib/u1_upd.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)

conf_check$(EXEEXT): $(conf_check_OBJECTS) $(conf_check_DEPENDENCIES) $(EXTRA_conf_check_DEPENDENCIES) 
	@rm -f conf_check$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(conf_check_OBJECTS) $(conf_check_LDADD) $(LIBS)
./src/debug_rng.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

debug_rng$(EXEEXT): $(debug_rng_OBJECTS) $(debug_rng_DEPENDENCIES) $(EXTRA_debug_rng_DEPENDENCIES) 
	@rm -f debug_rng$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debug_rng_OBJECTS) $(debug_rng_LDADD) $(LIBS)
./src/debug_su2.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

debug_su2$(EXEEXT): $(debug_su2_OBJECTS) $(debug_su2_DEPENDENCIES) $(EXTRA_debug_su2_DEPENDENCIES) 
	@rm -f debug_su2$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debug_su2_OBJECTS) $(debug_su2_LDADD) $(LIBS)
./src/debug_su2_adj.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

debug_su2_adj$(EXEEXT): $(debug_su2_adj_OBJECTS) $(debug_su2_adj_DEPENDENCIES) $(EXTRA_debug_su2_adj_DEPENDENCIES) 
	@rm -f debug_su2_adj$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debug_su2_adj_OBJECTS) $(debug_su2_adj_LDADD) $(LIBS)
./src/debug_sun.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

debug_sun$(EXEEXT): $(debug_sun_OBJECTS) $(debug_sun_DEPENDENCIES) $(EXTRA_debug_sun_DEPENDENCIES) 
	@rm -f debug_sun$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debug_sun_OBJECTS) $(debug_sun_LDADD) $(LIBS)
./src/debug_u1.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

debug_u1$(EXEEXT): $(debug_u1_OBJECTS) $(debug_u1_DEPENDENCIES) $(EXTRA_debug_u1_DEPENDENCIES) 
	@rm -f debug_u1$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(debug_u1_OBJECTS) $(debug_u1_LDADD) $(LIBS)
./src/yang_mills_gradient_flow.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_def.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_meas.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_multilevel.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_upd.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_paral_temp.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/gauge_conf_multicanonic.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/geometry.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/tens_prod.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)
./lib/tens_prod_adj.$(OBJEXT): lib/$(am__dirstamp) \
	lib/$(DEPDIR)/$(am__dirstamp)

yang_mills_gradient_flow$(EXEEXT): $(yang_mills_gradient_flow_OBJECTS) $(yang_mills_gradient_flow_DEPENDENCIES) $(EXTRA_yang_mills_gradient_flow_DEPENDENCIES) 
	@rm -f yang_mills_gradient_flow$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_gradient_flow_OBJECTS) $(yang_mills_gradient_flow_LDADD) $(LIBS)
./src/yang_mills_local.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_local$(EXEEXT): $(yang_mills_local_OBJECTS) $(yang_mills_local_DEPENDENCIES) $(EXTRA_yang_mills_local_DEPENDENCIES) 
	@rm -f yang_mills_local$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_local_OBJECTS) $(yang_mills_local_LDADD) $(LIBS)
./src/yang_mills_local_pt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_local_pt$(EXEEXT): $(yang_mills_local_pt_OBJECTS) $(yang_mills_local_pt_DEPENDENCIES) $(EXTRA_yang_mills_local_pt_DEPENDENCIES) 
	@rm -f yang_mills_local_pt$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_local_pt_OBJECTS) $(yang_mills_local_pt_LDADD) $(LIBS)
./src/yang_mills_local_pt_multicanonic.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_local_pt_multicanonic$(EXEEXT): $(yang_mills_local_pt_multicanonic_OBJECTS) $(yang_mills_local_pt_multicanonic_DEPENDENCIES) $(EXTRA_yang_mills_local_pt_multicanonic_DEPENDENCIES) 
	@rm -f yang_mills_local_pt_multicanonic$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_local_pt_multicanonic_OBJECTS) $(yang_mills_local_pt_multicanonic_LDADD) $(LIBS)
./src/yang_mills_polycorr.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_polycorr$(EXEEXT): $(yang_mills_polycorr_OBJECTS) $(yang_mills_polycorr_DEPENDENCIES) $(EXTRA_yang_mills_polycorr_DEPENDENCIES) 
	@rm -f yang_mills_polycorr$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_polycorr_OBJECTS) $(yang_mills_polycorr_LDADD) $(LIBS)
./src/yang_mills_polycorr_long.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_polycorr_long$(EXEEXT): $(yang_mills_polycorr_long_OBJECTS) $(yang_mills_polycorr_long_DEPENDENCIES) $(EXTRA_yang_mills_polycorr_long_DEPENDENCIES) 
	@rm -f yang_mills_polycorr_long$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_polycorr_long_OBJECTS) $(yang_mills_polycorr_long_LDADD) $(LIBS)
./src/yang_mills_polycorradj.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_polycorradj$(EXEEXT): $(yang_mills_polycorradj_OBJECTS) $(yang_mills_polycorradj_DEPENDENCIES) $(EXTRA_yang_mills_polycorradj_DEPENDENCIES) 
	@rm -f yang_mills_polycorradj$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_polycorradj_OBJECTS) $(yang_mills_polycorradj_LDADD) $(LIBS)
./src/yang_mills_t0.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_t0$(EXEEXT): $(yang_mills_t0_OBJECTS) $(yang_mills_t0_DEPENDENCIES) $(EXTRA_yang_mills_t0_DEPENDENCIES) 
	@rm -f yang_mills_t0$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_t0_OBJECTS) $(yang_mills_t0_LDADD) $(LIBS)
./src/yang_mills_tracedef.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_tracedef$(EXEEXT): $(yang_mills_tracedef_OBJECTS) $(yang_mills_tracedef_DEPENDENCIES) $(EXTRA_yang_mills_tracedef_DEPENDENCIES) 
	@rm -f yang_mills_tracedef$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_tracedef_OBJECTS) $(yang_mills_tracedef_LDADD) $(LIBS)
./src/yang_mills_tube_conn.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_tube_conn$(EXEEXT): $(yang_mills_tube_conn_OBJECTS) $(yang_mills_tube_conn_DEPENDENCIES) $(EXTRA_yang_mills_tube_conn_DEPENDENCIES) 
	@rm -f yang_mills_tube_conn$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_tube_conn_OBJECTS) $(yang_mills_tube_conn_LDADD) $(LIBS)
./src/yang_mills_tube_conn_long.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_tube_conn_long$(EXEEXT): $(yang_mills_tube_conn_long_OBJECTS) $(yang_mills_tube_conn_long_DEPENDENCIES) $(EXTRA_yang_mills_tube_conn_long_DEPENDENCIES) 
	@rm -f yang_mills_tube_conn_long$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_tube_conn_long_OBJECTS) $(yang_mills_tube_conn_long_LDADD) $(LIBS)
./src/yang_mills_tube_disc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

yang_mills_tube_disc$(EXEEXT): $(yang_mills_tube_disc_OBJECTS) $(yang_mills_tube_disc_DEPENDENCIES) $(EXTRA_yang_mills_tube_disc_DEPENDENCIES) 
	@rm -f yang_mills_tube_disc$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(yang_mills_tube_disc_OBJECTS) $(yang_mills_tube_disc_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f ./lib/*.$(OBJEXT)
	-rm -f ./src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./lib/$(DEPDIR)/aligncheck.Po
include ./lib/$(DEPDIR)/dSFMT.Po
include ./lib/$(DEPDIR)/endianness.Po
include ./lib/$(DEPDIR)/function_pointers.Po
include ./lib/$(DEPDIR)/gauge_conf_def.Po
include ./lib/$(DEPDIR)/gauge_conf_meas.Po
include ./lib/$(DEPDIR)/gauge_conf_multicanonic.Po
include ./lib/$(DEPDIR)/gauge_conf_multilevel.Po
include ./lib/$(DEPDIR)/gauge_conf_paral_temp.Po
include ./lib/$(DEPDIR)/gauge_conf_upd.Po
include ./lib/$(DEPDIR)/geometry.Po
include ./lib/$(DEPDIR)/gparam.Po
include ./lib/$(DEPDIR)/random.Po
include ./lib/$(DEPDIR)/su2.Po
include ./lib/$(DEPDIR)/su2_upd.Po
include ./lib/$(DEPDIR)/sun.Po
include ./lib/$(DEPDIR)/sun_aux.Po
include ./lib/$(DEPDIR)/sun_upd.Po
include ./lib/$(DEPDIR)/tens_prod.Po
include ./lib/$(DEPDIR)/tens_prod_adj.Po
include ./lib/$(DEPDIR)/u1.Po
include ./lib/$(DEPDIR)/u1_upd.Po
include ./src/$(DEPDIR)/conf_check.Po
include ./src/$(DEPDIR)/debug_rng.Po
include ./src/$(DEPDIR)/debug_su2.Po
include ./src/$(DEPDIR)/debug_su2_adj.Po
include ./src/$(DEPDIR)/debug_sun.Po
include ./src/$(DEPDIR)/debug_u1.Po
include ./src/$(DEPDIR)/yang_mills_gradient_flow.Po
include ./src/$(DEPDIR)/yang_mills_local.Po
include ./src/$(DEPDIR)/yang_mills_local_pt.Po
include ./src/$(DEPDIR)/yang_mills_local_pt_multicanonic.Po
include ./src/$(DEPDIR)/yang_mills_polycorr.Po
include ./src/$(DEPDIR)/yang_mills_polycorr_long.Po
include ./src/$(DEPDIR)/yang_mills_polycorradj.Po
include ./src/$(DEPDIR)/yang_mills_t0.Po
include ./src/$(DEPDIR)/yang_mills_tracedef.Po
include ./src/$(DEPDIR)/yang_mills_tube_conn.Po
include ./src/$(DEPDIR)/yang_mills_tube_conn_long.Po
include ./src/$(DEPDIR)/yang_mills_tube_disc.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f lib/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./lib/$(DEPDIR) ./src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./lib/$(DEPDIR) ./src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
